{% set name = "bip-utils" %}
{% set version = "2.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ebellocchia/bip_utils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b0bb13c290a1a0d704f0f114bd0c8ca4010936badc49f7f66325d53609d9f40f
  patches:
    - fix-requirements-conda.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - cbor2 ~=5.1
    - coincurve >=15.0.1,<20.0.0
    - crcmod ~=1.7
    - ecdsa ~=0.16
    - ed25519-blake2b >=1.4.1,<2.0.0
    - py-sr25519-bindings >=0.1.3,<2.0.0
    - pycryptodome ~=3.15
    - pynacl ~=1.5
    - python >={{ python_min }}

test:
  imports:
    - bip_utils
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - python -m pytest -v tests
  source_files:
    - tests

about:
  home: https://github.com/ebellocchia/bip_utils
  summary: 'BIP Utility Library'
  description: |
    This package allows generating mnemonics, seeds, private/public keys and addresses for different types of cryptocurrencies.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
